### ISSUE TITLE
allow to set maximum column width for autosize columns

### ISSUE THREAD

**Issue by SimonHeimberg** [krzysztofruszczynski/Krsc-Reports-PHPExcel-Framework#13]
This is obsolete or much simpler if https://github.com/PHPOffice/PhpSpreadsheet/issues/275 is done. See explication and code example there.

**Comment by krzysztofruszczynski** [comment]
If I understood it correctly, it is implemented in `\AbstractView::KEY_COLUMN_MAX_SIZES` option for view.
