### ISSUE TITLE
Support for private services definition

### ISSUE THREAD

**Issue by markussc** [krzysztofruszczynski/Krsc-Reports-PHPExcel-Framework#15]
It seems that there is a problem when services relying on the Krsc-Reports-PHPExcel-Framework bundle are defined private by default.
Refer to https://symfony.com/blog/new-in-symfony-3-4-services-are-private-by-default

**Comment by krzysztofruszczynski** [comment]
Symfony services are not defined in that vendor. They can be used in projects in various ways.
