### ISSUE TITLE
make all config optional

### ISSUE THREAD

**Issue by SimonHeimberg** [krzysztofruszczynski/Krsc-Reports-PHPExcel-Framework#4]
The minimal working config for `\KrscReports\Views\SingleTable` is:
```php
$config = array(
    'document_properties' => array(),
);
```

I suggest to make document_properties optional as well (is same info as empty array).

**Comment by krzysztofruszczynski** [comment]
implemented: d5e3d47045cb77bfb4b3fbe3fe0dac49c152e469
