### ISSUE TITLE
explain how the writer is generated (in README)

### ISSUE THREAD

**Issue by SimonHeimberg** [krzysztofruszczynski/Krsc-Reports-PHPExcel-Framework#9]
in [README.md](https://github.com/krzysztofruszczynski/Krsc-Reports-PHPExcel-Framework/blob/4610b2b95d8863534523080e6cfb32e1fd921677/README.md#L67) (after line 67) there is explained how to create a phpexcel writer. But is looks unrelated to the phpexcel object `$oElement` created before. How does it know how to get the right $oElement?

Reading https://github.com/krzysztofruszczynski/Krsc-Reports-PHPExcel-Framework/blob/master/Classes/KrscReports/Service.php#L142 does not help eater. I do not see the relation between `$oFile` and `$this->reportView`, and I do not see any phpexcel object.

I'd like to get the generated phpexcel object to do some post processing. And the writer to fix #2.

**Comment by SimonHeimberg** [comment]
found the excel object, it is stored statically: `\KrscReports_Builder_Excel_PHPExcel::getPHPExcelObject()`

**Comment by krzysztofruszczynski** [comment]
Currenlty, PHPExcel writer is created at the beginning with command `\KrscReports_Builder_Excel_PHPExcel::setPHPExcelObject( new PHPExcel() );`  . After that, all logic uses this instance, which can be always reached by `\KrscReports_Builder_Excel_PHPExcel::getPHPExcelObject()` . This is static with purpose.
